#!/usr/bin/env python
import numpy as np

import rospy
from hockbot.srv import (
    MovePickerCart,
    MovePickerCartResponse,
)
from sensor_msgs.msg import JointState

import actionlib
from hebiros.msg import (
    TrajectoryAction,
    TrajectoryGoal,
    WaypointMsg,
)
from hockbot.fourdof_kinematics import (
    FourDoFKinematics,
    SURFACE_PLAY,
    SURFACE_COLLECT,
)
from hockbot.inverse_dynamics import plan_trajectory


class PickerController(object):

    def __init__(self):
        self._hebi_commander = rospy.Publisher(
            '/hebiros/picker/command/joint_state',
            JointState,
            queue_size=1)

        self._cur_pos = rospy.wait_for_message(
            '/hebiros/picker/feedback/joint_state',
            JointState)
        self._pos_sub = rospy.Subscriber(
            '/hebiros/picker/feedback/joint_state',
            JointState,
            self._pos_cb)
        self._kin = FourDoFKinematics()
        self._cart_srv = rospy.Service(
            '~/move_picker_cart',
            MovePickerCart,
            self._move_cart_cb
            )

    def _pos_cb(self, msg):
        self._cur_pos = msg

    @property
    def fourdof_cur_pos(self):
        cur_pos = self._cur_pos
        cur_pos_dict = {name: cur_pos.position[i] for i, name in enumerate(cur_pos.names)}
        return np.array([
            cur_pos_dict['Picker/0'],
            cur_pos_dict['Picker/1'],
            cur_pos_dict['Picker/2'],
            cur_pos_dict['Picker/4'],])

    def jointstate_fourdof_angles(self, angles):
        """Convert fourdof angle command to 5-DoF command."""
        joint_names = ['Picker/0', 'Picker/1', 'Picker/2', 'Picker/3', 'Picker/4']
        joint_pos = angles[0:3] + [0] + angles[3]
        return JointState(
            names=joint_names,
            positions=joint_pos,
            velocity=[0]*len(joint_names),
            effort=[0]*len(joint_names))

    def _move_cart_cb(self, req):
        assert req.move_time > 0.2, 'move_time too small'
        if req.joint_space_interp:
            raise NotImplementedError('Joint movement not supported')
        else:
            traj = self.plan_cartesian(np.array([req.x, req.y, req.z]), req.tool_vertical, req.move_time)
        self._send_hebi_command_traj(traj, 0.01)
        return True

    def _send_hebi_command_traj(self, joint_states, dt):
        """Sends a trajectory to robot by streaming to
        command topic."""
        rate = rospy.Rate(1.0/dt)
        for j in joint_states:
            self._hebi_commander.publish(j)
            rate.sleep()

    def plan_cartesian(self, goal_pos, eff_vertical, goal_time=5.0, dt=0.01):
        eff_surface = SURFACE_PLAY if eff_vertical else SURFACE_COLLECT
        start_pos = self._kin.fkin(*self.fourdof_cur_pos)
        def interp_pos(fraction):
            print('start_pos: {}'.format(start_pos))
            print('goal_pos: {}'.format(goal_pos))
            print()
            return start_pos + (goal_pos - start_pos)*fraction
        positions = []
        for frac in np.linspace(0.0, 1.0, goal_time//dt):
            step_pos = interp_pos(frac)
            print('Step_Pos: {}'.format(step_pos))
            solution_angles = self._kin.ikin(*step_pos, eff_surface)

            jstate = self.jointstate_fourdof_angles(solution_angles)
            positions.append(jstate)
        return positions


def main():
    rospy.init_node('scara_controller')
    controller = PickerController()
    rospy.spin()


if __name__ == '__main__':
    main()
