#!/usr/bin/env python2
from ximea import xiapi

import cv_bridge
import rospy
from sensor_msgs.msg import Image


def main():
    rospy.init_node('ximea_camera')
    cam = xiapi.Camera()
    cam.open_device()
    cam.set_imgdataformat('XI_MONO8')
    cam.set_exposure(2000)

    img = xiapi.Image()
    cam.start_acquisition()

    bridge = cv_bridge.CvBridge()
    img_pub = rospy.Publisher(
        '/ximea_camera',
        Image,
        queue_size=1)

    while not rospy.is_shutdown():
        cam.get_image(img)
        cv_img = img.get_image_data_numpy()
        img_pub.publish(bridge.cv2_to_imgmsg(cv_img, 'mono8'))
    cam.stop_acquisition()
    cam.close_device()


if __name__ == '__main__':
    main()
