#!/usr/bin/env python2
import argparse

import rospy

from sensor_msgs.msg import JointState
from hockbot.gravity_comp import joint_gravity_torque
from hockbot.utils import (
    blocking_trianglewave,
    remap_joint_state,
    quadratic_interp_joint_state,
)

JOINT_INDEX = 0
AMPLITUDE = 0.00
PERIOD = 10.0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('joint_index', type=int)
    parser.add_argument('amplitude', type=float)
    args = parser.parse_args()
    rospy.init_node('move_triangle_wave')
    cmd_pub = rospy.Publisher(
        '/hebiros/picker/command/joint_state',
        JointState,
        queue_size=1)
    cur_pos = rospy.wait_for_message(
        '/hebiros/picker/feedback/joint_state',
        JointState)
    cur_pos = remap_joint_state(cur_pos, ['Picker/{}'.format(i) for i in range(5)])
    blocking_trianglewave(cmd_pub, cur_pos, args.joint_index, args.amplitude, PERIOD, joint_gravity_torque)


if __name__ == '__main__':
    main()
